# Generated by Django 5.0.1 on 2024-01-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDeco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('medida_alto', models.IntegerField()),
                ('medida_ancho', models.IntegerField()),
                ('materiales', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
