# Generated by Django 5.0.1 on 2024-01-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDeco', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='espejo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='espejos'),
        ),
        migrations.AddField(
            model_name='sillon',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
