# Generated by Django 5.0.1 on 2024-01-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDeco', '0004_espejo_imagen_sillon_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampara',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='lamparas'),
        ),
        migrations.AlterField(
            model_name='sillon',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='sillones'),
        ),
    ]
