# Generated by Django 5.0.1 on 2024-01-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDeco', '0006_alter_espejo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espejo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='espejos'),
        ),
    ]
